### ISSUE TITLE
Package.json format

### ISSUE THREAD

**Issue by sebasgarcep** [ajmnz/prisma-import#101]
Hey! I've been trying to set up `prisma-import` on a new project using `package.json` settings. I tried the following settings:

```json
{
  "prisma": {
    "import": {
      "schemas": [
        "schema/config.prisma",
        "schema/models/**/*.prisma"
      ],
      "output": "schema/schema.prisma"
    }
  }
}
```

But when I run `npx prima-import` I get the following error:

```
/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/minimatch/minimatch.js:125
    throw new TypeError('invalid pattern')
          ^

TypeError: invalid pattern
    at assertValidPattern (/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/minimatch/minimatch.js:125:11)
    at new Minimatch (/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/minimatch/minimatch.js:166:5)
    at setopts (/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/glob/common.js:118:20)
    at new Glob (/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/glob/glob.js:132:3)
    at glob (/Users/sebastian/.npm/_npx/56402732312c327d/node_modules/glob/glob.js:72:10)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at glob (node:internal/util:428:12)
    at /Users/sebastian/.npm/_npx/56402732312c327d/node_modules/prisma-import/dist/index.js:68:38
    at Generator.next (<anonymous>)
```

My guess is `prisms.import.schemas` cannot be a list? Is this a bug or intended?

**Comment by ajmnz** [comment]
Hi!

Correct, [this line](https://github.com/ajmnz/prisma-import/blob/main/packages/prisma-import/src/index.ts#L58) is transforming your `schemas` to `[["..."]]` and glob cannot parse it.

Feel free to add a PR to check if `config` is an Array.

Thank you!
